### ISSUE TITLE
The two data sets

### ISSUE THREAD

**Issue by BD-MF** [thumbe3/label-noise-nlp#4]
Can the processed data used be uploaded?

**Comment by sid7954** [comment]
Hi!

You can access the raw dataset files from the following links:
* [AG-News](https://github.com/mhjabreel/CharCnn_Keras/tree/master/data/ag_news_csv)
* [TREC](https://emilhvitfeldt.github.io/textdata/reference/dataset_trec.html)

You can then use the [add_noise.py](https://github.com/thumbe3/label-noise-nlp/blob/master/add_noise.py) script provided by us to inject different types of noises in the datasets. We cannot provide the processed dataset files due to the non-distribution license of the original datasets.
